[package]
name = "gif_to_ascii"
version = "0.2.0"
edition = "2021"

[dependencies]
image = "0.25.5"
num_cpus = "1.16.0"
rascii_art = { version = "0.4.5", path = "RASCII" }
rayon = "1.10.0"
regex = "1.11.1"
text-to-png = "0.2.0"
threadpool = "1.8.1"
